server:
  port: 8877
spring:
  h2:
    console:
      enabled: true
      path: '/h2' #http://localhost:8877/h2/
  jpa:
     defer-datasource-initialization: true
#    generate-ddl: false
#    open-in-view: false
#    hibernate:
      #ddl-auto: update  #spring boot entity 有修改時, 會自動修改 DB schema
      #ddl-auto: create  #spring boot entity 啟動時重新初始化 DB schema
  datasource:
    url: jdbc:h2:mem:fruitMarket
    driver-class-name: org.h2.Driver
    username: justin # database 用戶名
    password: 111111 # database 密碼